Vagrant.configure("2") do |config|
  config.ssh.username = "root"
  config.ssh.private_key_path = "insecure_key"

  config.vm.provider "docker" do |d|
    d.image = "atsaki/cloudstack-simulator-4.4.1"
    
    # if you want to build your own container uncomment following line
    # and comment out a line starts with d.image
    # d.build_dir = "."

    d.has_ssh = true 
    d.cmd = ["/sbin/my_init", "--enable-insecure-key"]
  end
end
