#!/bin/bash

export MAVEN_OPTS="-Xmx1024m -XX:MaxPermSize=500m -Xdebug -Xrunjdwp:transport=dt_socket,address=8787,server=y,suspend=n"
cd /root/cloudstack
exec mvn -Dsimulator -pl client jetty:run > /var/log/cloudstack_simulator.log 2>&1
