Vagrant.configure("2") do |config|
  config.ssh.username = "root"
  config.ssh.private_key_path = "insecure_key"

  config.vm.provider "docker" do |d|
    d.build_dir = "."
    d.has_ssh = true 
    d.cmd = ["/sbin/my_init", "--enable-insecure-key"]
  end
end
